<template>
  <div>
    <el-row class="title" style="color: #606060;">
    <img style="margin-right: 20px; height: 55px; width: 55px;vertical-align: middle;" 
         src="../../public/assets/img/blast.png" />
      Blast
    </el-row>
    <div class="myForm" >
      <el-input 
      class="RNAinput" 
      type="textarea" 
      rows="10" 
      placeholder="Enter the query lncRNA sequence(FASTA)" 
      v-model="textarea" 
      clearable></el-input>
      <div  style="margin-top: 20px">
        <b class="sou" >e-value: </b>
        <el-select v-model="eValue" clearable @change="evalue_change" style="margin: 0 20px 0 10px">
        <el-option v-for="item in options1" :key="item.value" :label="item.label" :value="item.value"></el-option>
        </el-select>
        <b class="sou" >word size: </b>
        <el-select v-model="word_size" clearable @change="word_change" style="margin: 0 20px 0 10px">
        <el-option v-for="item in options2" :key="item.value" :label="item.label" :value="item.value"></el-option>
        </el-select>


        <el-button 
        class="sou" 
        type="success" 
        v-on:click="Search(eValue,word_size)" 
        style="margin-left: 10px; padding-left: 10px" 
        icon="el-icon-search" plain>Blast</el-button>
        <el-button 
        class="sou" 
        v-on:click="SearchExample()" 
        plain>Example</el-button>

        <el-table
        :data = "tableData"
        v-show="show"
        border
        stripe
        style = "width:100%;margin:20px auto 0 auto"
        strip highlight-current-row>
          <el-table-column type="expand">
            <template #default="props">
              <el-form label-position="left" inline class="demo-table-expand" >
                <el-form-item label="Name:">
                  <span>{{ props.row.Name }}</span>
                </el-form-item>
                <el-form-item label="NONCODEId:">
                  <span @click="toUrl_NONCODE(props.row.NONCODEId)" class="hand">{{ props.row.NONCODEId }}</span>
                </el-form-item>

                <el-form-item label="NCBI gene Id:">
                  <span @click="toUrl_NCBI(props.row.NCBI_gene_Id)" class="hand">{{props.row.NCBI_gene_Id}}</span>

                </el-form-item>
                <el-form-item label="Aliases or Full name:">
                  <span>{{ props.row.Aliases_fullName}}</span>
                </el-form-item>
                <el-form-item label="Reason:">
                  <span>{{ props.row.Reason }}</span> 
                </el-form-item>
                <el-form-item label="Organism:" >
                  <span>{{ props.row.Organism }}</span>
                </el-form-item>
                <el-form-item label="Gene Ontology Annotations:">
                  <span style="width:80%">{{ props.row.Gene_Ontology_Annotations }}</span>
                </el-form-item>
                <el-form-item label="Sequence:" >

                  <span class="newlist" v-html="props.row.Sequence">
                  </span>
                </el-form-item>



                
              </el-form>
            </template>
          </el-table-column>

          <el-table-column
            label="Name"
            prop="Name"
            width="100">
          </el-table-column>
          <el-table-column
            label="Organism"
            prop="Organism"
            width="100">
          </el-table-column>

          <el-table-column
            label="Subject seq id"
            prop="sseqid"
            width="230">
          </el-table-column>
          <el-table-column
                label="Percentage(identical matches)"
                prop="pident"
                width="250" >
          </el-table-column>
          <el-table-column
            label="Alignment length"
            prop="length"
            width="200">
          </el-table-column>

          <el-table-column
            label="e-value"
            prop="evalue"
            >
          </el-table-column>
          <el-table-column
            label="Bitscore"
            prop="bitscore">
          </el-table-column>

        </el-table>    

      </div>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import { ElLoading } from 'element-plus'
// import {showLoading,hideLoading} from '../assets/js/loading.js'
export default {
  data() {
    return {
      example: `>NC_000074.7:c121809849-121781621 Fendrr [organism=Mus musculus] [GeneID=68790] [chromosome=8]
CGGGTTCCGGAAAGCGGGTGGCGCAGGCGGGGAGCGCGTCAGGGAGCGGCCCTGGCTGCGGGGTCGCGGC
CTTGGAGAGATGATGCGGGGCGCAGGACGATTCACGATCCCAGGTGGACTTGCGCGCTCGAAACCAGGTG
AGTGTGGGCCTTCCGCAGCCCAGACACGCGCGCGCGCGCGCGGGAAGCCCTAGTGGCAGGGCGGGTGACG
AAGGGGACCTTTACAGGAGTTGGTGCGAGGGACCTTGGAGCTAGGCGGCTGCGCCCTGGCGCGAGTTGCA
AGAAGAGATGTCTGCGGGTCTCCTTCAAAGCCCGCTGGCCTCAAGTTTCTTTGGATTCTCGGTTCCCCAT
CTTCTCCCCACCCCCACGCCTTCAGCTTTGGTGGTAGGCGCCTTGTCGTCTTCGAGGCGCCTGGCACATC
TGTGCGAGGGTCTGGGGGCTTACTGACTTAGGTTGTTGCTCTGTAGCTGCCTCCTTTGGCAGAACCGGGT
TCGCAGGAGGCGAGAGTCGCCATCCCGTTCCTTTCTCCAGGACAGACTTTAGAACTCTGTGGTCCAACTA
AATTAAAAGGGAGGAAGAAGGGAGGTGGACGCTTATGTGTGGTTATGTGTTCGTGCACATAGACGCTCTA
GCAAGCCGGCTTCTGCGCCACACAGTCGGCCTAGACAGCACCCCTCAGCACCATCCACAGACTGGCGTCT
GCCTTCTCACGGGACTTAAGTACAGTTAAGGGGCCCCACCCTGGAAGGGCGCACCACATGTAGCCTGCAC
GCTGCTGGACTGTGCCTTCGCCCACACAGAGCCACAGGATCACAAGAATGGGCCTTGTAGGCCAGAGCGC
ACCCTTCCACCCCAGGCCACACATTCCCACACCCCCAAGTTTTCTTCTCCCCCCCTTTCTCCTTTCTTTT
CCTCTCCATTATTTTCTTTTTATTTACGGTTTGTTTTTTTTTTTTTTCCTCTTACACTGGCAATTGCAGA
CCTGAGGACTCTGGGCTGTACCTCAGGGAGGGAAGTTCTCAGAAGGGCGCTACATAGCTGGCCTTTAGCG
AGAAGTGAGCTGAGGAAGGCGCCCATTTTCCGAGCCGGCACAGGCTGTATTTTGCATGCTGCCCCAGTCC
AGCCTTGCCTCTGACCTCAGATCAAGGGTGCCTCCAAATCGAGGGGACGTGAAGCTCTTTTCCAGTTAAA
GGATGTGTGCCCATAGGTGACCTCCAGATCTGCCCCCCTTCCCGAACTCCCACAGACCGCTGTCAGAGGC
TCTTTAGGGTATTTTGTAGAGAAATTTCCTTTTCAGGGGAGGAAACTGAAGTTTCATTTGCCCTTCAGTC
TTCAGGCCTACCTCCTAAGGCTGCCTGTGAGGGGGAGGGTCAGGGGAGCCCAGTTGCCTGAGGCTCAGCC
CGAATTCCCACTTTCCACTGAGGAGAGAGATGGAAGTGGGTACCCAAGAGGGTAGGAACCCTGAAAGCCT
ATAGCTTGGATGACCCTCTACAGTTATAAAGCAATGAGGGTTGGGGGGAGTTGCCTATGTGTCTCGAAAC
AGCTCGCAGACACTTTGAGATCTCTCTGAATCCCACATTTTTAAAGAGGAGAAACGGAGGTTCAGTCATA
GGGCTCTATCAGTGGCTTCCCTTGCTGGACGAGTCTCCTGGCCCCATAAACTATCTCCAACCGATGCTTT
TATAAAGTGTCAACTGAAACTGGGGCGGGAGGGGGTGGGAGGAAGCCAAGCTCTTGGTCATTTTGTGTAA
CTAGGATGAGACTGACTTCAGGAGCAGGGTCATCATGCCTCCCTCCTAAGAGGCCGCGGGGACCGCTTCC
CCCCCCCCCCCCCATATTTCAGTGTAGGATCACTCACAAGTCTGGATGGTCCCAGCCTAGACCATTTTGT
ATGGAGCCAAGTTTCTCCCTTTAAACGCGGCTCCAACTAAAGCACCCACTTCTTACGGTTGTGGCAGCAG
TGAGCTGGGACGAATGTCACACAAAAGTCCCCCGGGGGAGCAGCCTCAGGGAGGCAGGGCCCTGGATCCA
TAGGGTGATACCTGCTCTCAGCTGAAAATCCACAAGACTCCCTCCGCATCTCAAATCAAATCCCTGCGCT
TAGCACTGGCTCCAGGAATGCCCGCATTTCGGGGAGGACGCCCCCCACTCCGGGGCCCCAGGTATCTGCG
CTGGTTAATTGCTTAAGTGAAGCCGCCGGCCGAAAGCGCGCCCGGCGAAACCCGAGCGCGGAACCAGATC
CTGCTTCGGCCGTCCGGCCGCGGGCGCCGCCGACCACCCACAGCGAGGCCGGCCGCCCTGCTGCAGGTTA
GCAAGGGCCGACCCCACGCGAGACTGCGCATCCCCGACATCCAGAGGGAGCGCGGGGGACGCGCCGAAGT
GCAGGGATGGAGAGGGGAGGGAACGTGATACGGACAATTCAGCCTTTGGGTACCAGAATTCAGAGTGCCA
CTTGCCCGATGAGGTAACTGTGGGCAAAGTGCACGGTGGGACAGGCACCACGGACTGCCAAGGGAACTGT
AGAGCGAGGGAGATGTAGAGGGGTGAATGGATAGCAAACGAATACCATGCCTTAAGCCCTGGAGGACCTG
GGGCTGGTGTGGTGGCTTCATGTGCAATCAGTGTTTGAAGATTCTAACTGGGCAGGACTCTCCTTCAGTC
TATCCACCGGCCTGGTTGGTAGATTGCCCAACTAACGTGTGTACAGAAAGGTGAGGTGATCGGTAATCCC
AGCATTCCCGAGGTGGAGTCGGGAGGAGCTGAAGTTCAAGGTCATCCTTGAGTTTAGCAAATTCAGGGCC
AGCCTTGGATATCTGAGATCCCTGTCCCCCAGATTAAAAAGCAAACAAACGTGAAGGACACGCCCTGTAT
ATGCACGAGCAACGCGGGATTGTGAGGTGTAATTACCTGCAGAGCGGGACTGCTTTATGCACAGTGGAGG
AATGTGGACAGGACTGTGTGTTACAGGCGGAATGTTCTGAAGTGTTCTAAATATGTGCCCAGAAGGTAGA
AGAGCGTAACTCTACAGGCCTCAGGAAAAACGGCGGCCTTGAGAGCGCTGTGGGCGGGTTTCTGTCAGGG
GTGTAGGATGGGGTACCCTTGAAACAAGGCTTGAGGCAGCTACTTGTATTGGGGTGCACTTTAAAGTAAG
GAAGGGCTGGGTGTTCTGCTTAGCCAAAGTGGGGGGGGGGACTTGCTGTCAGTGAAAGGAGGTGAGGGGA
GCAGAGGGACGGTCACTGTCAGCATCTAAAACCTGTATCTCCGACAGACAGCCACTTAACCCAGAACAGG
TTAATAATTTAGTTAAAAAAATAAACTAATAAATTGTGCTGTGGATGTGGCACAATTGGCAAAAACCCAA
ACAAACAACAGGTGTACAAAACAAAATCTTCCAAACAAAAACCAAAAAAGTCACTTGTCAAGCGTGCACA
GAGCCCTGGGTTCCACACCAGAACCAGATAAATCAGGCTTGTTACAAGCCTGTAATCCTGTCGCTTGGGA
AGTAGAGACAGGAGGATCAGAAATTCAAGGCCCTTCTGAGCTACACATTGAGTTTAAGGGTGGCCTGGGC
TCCGGGACGCTGTCTAAACAAGTAAATAAGAGGGTCAGCACTCAGTGCCAAAGAAGCCTGAACTTGCTTC
TTCCCAGTGGCCCTTATATCCCAAAGCGTCATTTTCCATGACGTCCTTCAGTGAAATATTTGATGGTACT
ACAGTCCCGGAATTTACAGCTCTTCCCAAAGAGACAGTCCGGAGCAGTTCCCGGATCCTGCTACTCCAGG
ATGGGTAGGTTCCTGGGCAGCTTTCTCCCCCCACTTCAGACACCCCAAACTATCTGCAAACATTTTAATT
CTAGCTGCCTGAGCAATTGTACTTAGATAGAGAGAAGGGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTCA
GAGCCAGAAAGAGACTGAGCCACCAGAGAGAATTTCTGGGGAGCAGGGAGATGCTCATCACCACAGAGAG
GTGAGGATACAGGAGGAGTTTGGGGAGGGGGATCCCAGAGAAATCAGGACTGAAGTGGAGAGGAAGCAGC
GTGAGCTTCGAAAACAAGCCACCAGGAAAACACAACGCGTATTATGTGTCAAGGGCCAGTTATTTTTATT
TTTATGTTGTTCATGTTTAGGAGAGATCCAGTAAGACAGAGCCCACACAGCACGCACACAGTCATCAGGA
ACACCCCGAGGGGAAGCGATTCGAGTCATCCAGAGAGGCTGCAGCCATGAGCTGAAACGGCCCCCCGGAA
ACCAGTTCAGGTTTGTTTCTTGAAAATCAGCAATTTGTAGCCAGCAGCCTGCTGGTGTGCAGGGCTCAGT
ACCCGGGTGGCTGCAGCGAGCAGCCTCGTTACAGCACGCTCAGCAGCTAGCCCCAGTAGCACCTTTAGAG
GACATGGAAAAGCGGGGAGACTGCTTTAGCAGAGAGAAACAAAGTCCACCCAGCCTAGGAGGCCGGCAAG
AGAGGAGGGAGCTCACCTGTCAGCTTCCAGCAAAAGACCCAGGCTTGGCTGAAAAAATAGGGGTGGCACC
CTCTTTGCACACCTCCTGCCATCTACGATGTGCTCTATATATATATATATATATATATATATATATATAT
ATATATATATATAGTATTGTGTGTATGTATGCACACACACGCGCGCGCGCGCGCGCACACACACACACAC
ACACACACACACACACACACACACATCCACATCCCCTCTCTCCTTTTATGTCCTAGCCAGGTTAGAAGGA
TTATATTTATACTCATGGTCAGACCTGCTTTGGTGCATCCAGGTCACAAGAATTCAGGGAATCAGAGAGG
AAAGGAGTTTGGAACATAGCTGGCACCTGCAATCCAGAAGGCTGAGGCAGAAGGATCTCCATGAATTTGA
GGAAGAAAAGAAAATTGGGATGGGAAGTCCGTGTGTGGGGGTGGGGGTTCATGCTCTGGATGAGGACAGG
AAAGGGGGTGGGGAGGCTCTCAATGGAAAGGGAGGACCAGGTGGAAGCAGAGTAAGGCCTCCTCCTCCTC
CTTCTCCTCCTCCTTGCATCGAGGCTTGAAGCCCAGGGTGAGAACCTTCAGTGTGAGTATGCTGCAGGAT
GGGGCTCTGCAGAGGGAAAAAGTGTGTGTGTGTGTGTGTGTGCATGCGCAAGTGTGTGTGTGTGTATGTT
CACGTGCCTGTGAATGTTTGTGAGCTCCTATGCCCTTATGTATGTGAGCACACACATCTGTGCATGTGTG
CATGATCCTATGCCCGTATGTGTGTACATGGACCTGTGTGCATCTCTGTGCGCCCGTGCATGTGTGATGG
GTGTGCACTCCTGTGTGTGTTCACGTGCCTATGAGTGTGTGCACGCTCCTATGCCTGTGTGTGTGCTCAC
GTGCCTGTGTGTGCATCTCTGTGTGCCTCATGTGCCTGTGCATGTGTGTATACTCATGTGTGTGTATACT
CGTGTGTGTGTGTGTGTATACTCGTGTGTGTGTGTAACTCTGCTCTGATTATCCACCGTTGGCACATAGA
GAAGATCCCAGAGGCAAAAATTACAGGACTGTCAAGGTTCTTGCCTCAGTTTCTTCATCTTGCCAACTGG
GTAATGTCTGACCATCCCTGGGCTGACCCAGGGATGCAGAGAAGAGAAACATCAGAACTAGTGTTCTAGG
AGCCTGGCCAGTCAGGGAGGGAAAGATGCTGTAAACTCAAACCATGTTAAATTGTTAACCGAACAAACAC
ACATAACCACTCCGGCCCTGTAGTGAGGATTTATGGTTACGTTTGGGTTCCATTGCTCTGTGGCTCAGAG
CCAGTGGCCTTGCCTCTCTGTGCAAACAAGAATAAGGATACAGCCTCTCTTCTGTGTGGTTGAGAGGACC
AGACATAGTAATTGTTGGCTCAGGTTGTTCTTCCCAAGGTGCAGAGATCCCAGGAGCCTTGCTCTTTACA
GGATTGAAGGTTGAGGGTTAATATCCCTCTTTGATGCAGCCACTCAAAGTTTTGGAGTCCTACTGGGCAC
CTGAGCTAATGGGAAGGAGGGTTGGAGGTGGAGGGACAGGTGAGGAACAAGTGCCTGCTTTCTGAGAGAA
GGATGTGGGCCCTTGGATAACACAAGGCACTTCCCACACGGAGAAGCTGGTGCCAGCCCAGGTGCCCCTT
TCCACGGAGCTGGTCCCGGCCTCAGTCCTGGATGTTTCCCACTCTGGTAGGGTGCTGTCTTGGGGCAGGT
TCCCTCCCCGTCCAGAGGCTGTGATTTCCAGGCAGGGTGATAAATGAATCACCGGCTTCCCTTCAGGGCC
ACCCTGAAGACTGCAGGGTAGCCTGGGGAAGCTCGGAGCACCTGCCAGCTTGGCCTGTTTCATGGTGGGA
CTGCTAAGCTTATCCAGGATGGTCTTAGTACCCTGACAGCTGGTTGAAGGGGCTTCCCTTTGGGATAGAT
GTGGAGGTCCCTAGCACATCTAGCGAGGAGGACCTGGGAGATTGGACGTCCTCAAGGCAAGCTTGATGCT
GGGTGCTCTAGCTTCCCACCAGCCACACACCTTTGTCTTTCTTTCCCTTTCATTTTCTTTTCTTTCTCTT
TCTCCCTCGTTCTCCTTTCTTTCCTTTTTGTTGTGTTTTTGGTTTTGGTTATTTGGGTTTTTGTTTTGTT
TTTTTACACCCCTCTGGCTGTCATGGAACTCTCTCAGAGATCTGCCTGCCTCTGCCTCTCCTTGAATGCT
GGGATGAAAGGAGTCAGACCCACATTCCACCACGGTTAACAAACGCACATCTCCAGTTCCCCATGCCCGC
TCTGCCACCCACCGGTTCTCTCCTGGCTGGGGCAGGAGGGCAGGGCGAGTGGGAGCGGGCGGGTGGTGGA
GCATTAGTTTCCCAGCAGCCCTTTCTCCTGCCCGTTTCTGAGAAGTGCCGGGAGCGGGTGGAGTGGGGCT
GGCTGACCACCTCTGGAGCAGCAGCGTCCTCAAAGCGGACCCATTGCCCAGTTGGTGACTCATCCTCTGA
TCTCCCTGGCTGGGGGAGGGGGGTTAAGAGAGAGTCGGTCAAGGTATGAACTTGGAAGAGAAGGGCTTTT
GAGCAAGGGGCTGCTATTTGGAGGCCAGAGCTCCCAGGTCCCGTCACAAACAGATTCGGGAGTGAGTGCA
TATGGGTCAGGGTCTCCATTTAGGGCCTTTGCAGAAACACACTGGTACCCTGAGTGTCCCTTAGTTCCTT
GCAGTTTATATTCTCTCCCTCCACCTCTGCCCTATGTCTCTGCCTCCCCTCTCTTTAGGGCTATTTTCGT
TTGTTTTTTGCCACCCACTCAACTTTCAAGGTGTTACCAGCCAACAGTATTTACTCCCCAACACATCCCC
AGCCTAGCCAGACAAATGGACACACAGAACAAAAGGAGTCAAAACCACAGCTGAGCTGTTTTCCTCATCG
CATTTTCTTTTCTTTTTTATTTTACAATTTATTTTCTCAAAGCTCAGAAGCACCCCCAGTTCTTCACAGT
TTCATCACTCGCAGTCCCCAGTCCCTGTTCGTTTTGAAAGGAATTTCCCCGTCTCACTCGTATTACTTGG
GGCTTCCCTACACCAGCACCAGGGAGCTCCCCCCCCCACACCCCGTGTTCTTAGTAGTTCTCAGTTAATT
GCCTGCAAAAATTCTGTCCTTGGCATGGGAGGATATTCATAATTAAATGCTTTTTTTTTGGAAAATATAA
AGGCAAACATAGTTCAAATATTTCGATCGTACTATCCTTAGGTCAGGTCTATTTGGAATCTTCCCTCGTT
CCTCCCTTCTCTCTGGGAAGACCTGAAGACAGCCCTCTGTCTTCTCTACTGCGGCCCTCTGATGGGGGGG
GTCATTATTTTTCCTGCAAATTGGGCTGAGACCTGTTTTAATTCGCCATGAAAACCAACCTAATTAGGAA
TCGAATTCGCTCTTTCGTGGGCTTGAACAAGCATTCTCTCCTCCCTCCCTCCCTCCTTCCCAGCTCTGAG
GGCTTTCTGAACTCCCTTCCTTTGGAAGTGAGCACCTTTGGCAGCCTCCTACCTGCTCCTAAGTCTTCCT
CTCTCTCTCTCTCTCTCTCTCTCTCTTTCTCCTTTATAAGCAGTTGAGACACACTCGATTCTGTGAGTCT
ACCGGGAGCATTTTTTTTCCATCGTAGTCTCCCGGTGGGGGAAAAACATCTCTCGATGGCCTTCGGCCGA
GGCGGTATGTTGTTGGTCTGGATGACCGGCAAAGCCCAGAAAGTACCATTAGCAGCTGACTGAGTCGGGT
TGGTTCTGGGCGGTTGACCCCAGCAGCAGCAGCAGCAGCAGCAGCGGGGTCTGAGTCCCCTAGGGCAAGG
CAGCAGGAGGGTGCCTGGCTGGTTCCCGTTGCTCTGTGCAGAGAGCAGTTCTTTTACTGCGGTTGGACTA
ATGACGGGTCCTGATTTTGTGAACTCGGTGTTTATTTTCCCTCCACCAGCCGGGGGAGGAGTGCAAACTG
GGGAAAGACCCTCGGGACAAGATCCCTCCGTTCTTCTGGGAAACTGGCTGAGGCTCTCTCCCAATGCACC
CCATCTCCACACATACCAGCTGGGCAATGGCCATTCTGGGTTGGGATTAAAGTAGGTTTCCACCTTTCTT
CCCTTCTGCTCTTGCCATTGGGTGGGGGGGGGGCGGTCAGGGGACCAAGGCACAGGGATACACATCAGCC
ACTTTCTGGGGGGACCCACTTCAGCACCTTCTGCCCTGGACATCTCCTTTGGACAAGTTCTGAGTACTCA
ACCCTGGGTACTGGCAGCCTCCACCTTGGGGCCTGGAGGGAAGAAATGAGCAAGGGTGCAGCCCAGGCTG
CCTCTGAGGTGAGGTGACCACGTCTGTGGACATGAAAACCCAAGAAGTGTTTGTTACACTGGGAGACGTG
GATTCAGTCATGCAAAATCCTCAGAAGACACATCAAGAGGGGGTATTGTTATATCGAGGCTTAGCCTGAG
CCAGTGGCAAGGCCGGCTTCCCGCTTCACCTGCCCTGGAAGCCGGCGGAGTCTGGTTAATTTTTCAATGT
TCATTTCCAGCGATCACAGGGCCCAAATGGAAACCAGAGAGCTCCGAATAGGCCACAGCGGTCAGTTACC
CAGGACTGCAGAGACACCCTTCACTCCTGCATGCGTTTGATCTGACTCCACCAGAAGGTCCAGTCGCCAA
CGCCTAGCTGAGGTCCCAGGCCAGGCCTTACCCCCAACCCCTACCCTCTCAGCCTCCAATTGAAAGAAGG
CCTGCCGGCTCCAACTCAATTAGCACAAAGGCGGCGGCGGGCACCCTGGTCTGTGCCGCAGGGCAGGGAG
CGTCCTGGCGGGCAGGTAGAGAGAAGTCCGCTAGCCCCGGGTGTTATCAGCAAGCGGCTTAATCAGGAAT
TTGAGCTGACAACGTGCGCACCGCCACCCGGCTCCGCCAGCCGGTTGACGGTGGGAGTGAGACCCGAGAG
GCTGGAGTCCCAGACTTCAAAGCTGCCCGAGGTGCGGCGGCCTTGGGGAAGGGGGCGCCCGGCGACAATC
GGCAACCCCGAGCGCCGCCTGGACAGAAGCCGGCGGGCCAGTGGGCGCTGGACCATCTTCCCTGCGAAGT
AGGTGGCCCTGTATATTTTTGTTCAAGTGGTGTTTACGTTAATGGAAAAGGGATGGGGTTACAAACAGCC
TACAATCGGAGTCAGGGGCCACTGGGGATTCCACACTGAAAGGGCTTTCACTTTGCCTGGAGAGACTTAG
CGGGAACCCGCCCAGCATGGGGTGGTGCTGCAGGAACCCCCCCCCCCCCCACTCCAACTCGTGCATCCGT
CTGGCTCTCCCGACTAGAAAACCCTACTGCCCCAGGCGGCAGTGCAATTGGGTTTACAGAGGAGAAAAAC
CTCGTTAAAGACCCAAAGGGCTCTTTCTAAAAGGGCCCTGGGAGGGCCTCCCCCTTCCCCACCAAGCCAG
ACTTTCCCTTTCTTTTCGTAGCAACAGAATTTGCCAGGAGTTCTCCAGAACTCCTGAGGAAATCTCCCTT
CTCCAGAGCAGTGGTCTGTCCAAACACAGACACAGGTCCCCCATCCCAAGACAATCTTTCCCCTCCTTTT
CGCCAACAACTGCATCTGTCCTTCTTTCTCCTCCTATTGAAAACAGGGAGAGCAGGCTGCAGGAACAGGC
TTCTGTCAAAGGAGAACTCAGAATACAAAAATAAAAGCAGGGGAGGTGGGTGGTAGTCCAAGTAGGTAGG
AGACGGGCAGCTGCTTGAACCAGGACAAGAGGGCTGACCGACTTTTGGAAAGGTGTTTCCAGTCTCTTTC
CAGGATAGCAGCTTGACCTGAAGTCAGACCCACTCAGGGACTGTCCACCCAGCTGACAGTCCACTCTGTC
AGCTCAGAGCCTTGTCCGATCTTTTCCTGGAAGATGGTGGACTGGGCAGTTAGGGTTATCTGACACACTT
CCGCTGTTGTGCAGACTAGATGGGACCTGGCCTCGGGGTGTGTGTGTGGTTGCTTGCAGGGAGAACGGGC
CCTGTCAACTTCCCACCTAGAGCGCTGAACATCAAGTCAGTTTTGGGGGCACCACAGTCTTCTCATTTAG
GGCCTTCTTCCCAACTGTAAAACGTCAGGAGCTTAACATGAGTGGGTTGGGATAGTGACCCCATAGGAAG
TTCCGGCACAAGCCTGTTCTTGGATGGGGTGTTCGTTCAAGAGGAGAGTTTTGGGTTTGAAAAAAATATA
TGTCTGTATTTACTTTTGAGATAGGGTCTTGCTTTACAGCATAACTGGAGCTCCCGAGCACTGGTCTTAA
ACTCACTGGGATTCTCCTGCCTCAGTTTCTGAAAGGCTGGGATGACAGGCCTGATGAACTCTAGGGCTAG
GCATCCAGCAGGCTCACACTCTCATGGGAAGCACTTGAGGTCTTGGCTCCTCTGTTCAGCCACCTTAGGG
CTGAGTGCTGAGCTCCTGGGCACTGGCTGGCCCCTCAGTGTCCCCACCTTTTGTAATGGAGCCAGTGACC
CAGCTGGGATTTGATTTTTCCTCCCTCCCTCCCTCCCTCCCTCCCTCCCTCCCTACCTCCCTCCCTTCCT
TCTTTTCTGGTCTATCATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTAT
CTATCTATCTAACCTATCTATAGACAGTTTTTCTCAGTAGTCCTATTGTCCTGGAACTTGCTCAGTAGAT
CAGGTTTGCCTCAAGCACAGAAGGCATACACCTCCGTGCTGGGCTTTTCTTAATTAGTCACCGAGAGATC
TTGGGTGGTGAGGGAGGTTCGTGGTTGTACTGGGGCAACAGCAGGCAGCACCTTGACTTTTCCCAGACCC
TGATGGTCCTAACCCACCAGAGCAGAACAAAGCTTTACTGGCAGCCAGCTGTCTTTGAAAGACGTTCTTC
AAACCCCGCGGACTTGTTGACACCCCTTTGACAGGCTCTGCTGCACTGACACTGAGCAGCCTCCAGAGGA
ATCCAAGCTTGCAGAGAGAAACGCAGAGCAAGGAGTCGGAAAGGGAAGCCTCTCTGTGGCTACAGGCCAG
CGAGGTTACAACTTCGTGCCCACGTTCCTGCCGGGCTGGGTGCTCAGTGGGCAGGGCACCCATCCATCTT
CTGGCTGACTGGTGGGCACAGGTGCAGTCTACGTCCTGTGTGCCATCAAATAGTGTGGGTGTGTAGTCTG
TCCTGTGCAGTGGCCAGCCTTTCCCTTTGCCCCTGGGGTGCAGGAGCAGGAGGGTATAAGAGAGTGAGCC
CTTCAGGATTAGGGTGGCCCTCATGTTGCCAGTCTGGGGTCTCCGGGGCTGAGTATCCCTGGTCCCAGGC
TTTCTCTGTCACTCCACTTTCTCCTAGGCCAGGGACACCAGATGCGAAGTCCTGAACGCGCTGGCAGGGT
CCCTTGTGTGCGCCCCAGACATTTCTTCCATCCTGCAATTAAACCCGAGGTCAAATATCTCCTTAACGAC
GCTATCAGGCCAGAGCCTCATTACAGCGTATATTTAGCCATAAAATAAGGGTTGTACGGAGCAGGGCATG
GAAATGACTGCATTCTGGGAATGAATCCTTTTAGCATAAACCAGGGTTGTTATTTACCACGAGAGCTAAG
TACAGGCTGGGCTTTCCAGGCGACCCAGGCAGGAGCAGCCGGCTTCCAGGCTCTTCTGGTATTGCCTGTG
CCCACCGCAGGCCTGGCATCTGCCTCTGAGTTGCTGCACTGCTGTGGACCAGGAGCTGATGTTCTGACAA
ATGCCCACCAGGCTTGCAGCTGGGACGCATCCTCCAGAGGACTGTACACAGGGGTGCTAGCAACAATATG
GGAATGGATAACAGTCTGCAGGCTGCTGGGCTGCCATGGGTGGGTTGGGTGGGTTACTCAGCCTCTCTGT
GCTTCTTCCCAGAACCCTTGAGAGGAGTTAACCCTTGAGAGCTCAGTGAAGGCTGCAGGTCAGGGAAAGA
CTACTAGAAGCAGGAAGGTCAGACTGGGGGTGCAGCTAGGTGGGAGAGCCTGCCTGAAGTCCTGGGTTGG
ATCCCATCACAAAAGAGGGGAGATGTGATGGGTAGGGGAGGAAGAGAAAGGGAGGAGAGGAGGGAGGGAA
GGAGGGGGAGGAGAAAGGGTGAGCTAGAGTAGAGGGTTAACTCTGGGTTGCTGGGAGGAATGAATAAGCA
GAGCCAGCATCGAGGGGCAGAGTAGAACTGGGGACCAGGGGAGAGGGCTGGACTTGGCCTCCCAGGCCAG
GCCCCAGGTTCCAGCCTGGGCTGAGCAGAAGAGCTTCCAAGTCACCCCCTTCCAGCCTCCTCTCTCACCC
CACTGCCCCATGCCGCACTGTCCTGGGGACAGGTGGCCCAGGTGGACCCAAAAATCTTTGGAACACACTG
AAGCCTCTCAGTTTCACTCTGAGGAACCAGGATTGTGTGGGCAGGCACATCCCAAATCCTGTCTCTCAGG
AAGTGGCTTGGGTGACCCTCAAGCTACAAATATTTGGATGTATCAAGAGGAGAGGAGGGAGTCCCCAGTC
TAAATGTTTGCCCGAGGTCTCTGGGGGGCAGATTAGTCACACACAGACACACGCATGCATGCACACCCGC
GCGCACAAACACACACACACACACCAGCTATGATCTAGAGGAATATGGGCTAGGTGTCCAGCCCAGCTGG
CCAAGGTTCAACTTTCAGCTTCCAGGTCAGACAAGATCAAGTAAGACCTTCTCCTTATACTCCATAATCC
TGCCTGGAGATCCTAAGTGTCTCACACAGTGGTGTGAGCTGTATTGGCTCGAGGATGGGCCTTCTAGGCC
CTGCCTGCTGGGACACACACATATACCACATACACACATGTACCACATAAACACATGGACACGGACACAT
ATGTACACGTGCACATAGTCTCTCGGCCTCCAGAACGCATGCTACTGCTCTCCTTCCTTAGTGACCATTC
AAAGTCCTAGGTGGGGCTGGGCCTGACCTCCAGGCTTGGTGAAGGGAGACAGTTCTTACCATCCTTTTCA
CATGTACATGAGCAGGCGCACGTGCGCGCGCACACACACACACACACACACACACACACACACACACACA
CACGAGCATTTTCAGGGCAGGTCACTGGAGCTCTATGGTGGCAATATCGTGTGACCCTGGGAAGGAAATG
GTAGGTTCTCCACAGGGGTTCAGTCCCCACAGCCCTTTGAGGCAGGTGCCCTTATCCTATTCTCCCTGTT
TCTCAGAATCAAAGAAGTTAAATGAGGAGCCAAAGGGGAAGGGGTCACAGCATTCATCTGGGCTTGAAGA
ACCTGTGACCTCTGAGGCTTGTGTTACTTTCAGTGTGTTTGAAAGGCTTGGGGTCCACCTAGGCCACCAG
TTCCCAGGATGGTGAGGTACAGGACAGTGGGGTGAGAGAGGAAACTGGAAGGGGGTGACTTGGAATCTCT
TCTGCTCAGCCCAGGCTGGAGCTGAGGGAGGCAACCTGGGACCTGGCCTGGGAGCCCAAGTCCAGCCCTC
TCCTCTGGTCCCCAGCTCTCCTCTGCCTCTTGCTGCTGGCTCTGTTCACTGTGTTGGTTGGTGGTTAGGA
GGCAAACAGAGGGTTTGTTCCCAGGAGAGCAGTGAGGCTCACAGAGGCTAAATGAGGAGACAGGGATTTG
ATGAGAACCTGTGGAGGTGGAGGGGTCCCCCCAGGGTGTCACAGTGGGGAGTGGGAGAGGTGGAGGGACT
CCAGGAGCTCACACTAGGGAGTGACGGAGCAGAGTGAGGATCCAGACCAGGGGCTGAGCTGGATGGAGAG
ACTGAGTCCTCAGGGGTGCTGATGCCCTATATCACGTGACCTTCAGGGATTGAGTTTGCAGCTCAGTGGG
GTTCACTTCCCACTGGAAGGTGCTGAAGAAGTGTCTGGGTGCTGAGTCCTTAATCTGTGCCTGTCACTGA
GGGCTTTTAAGCACCTGGAATCACAGTGTGTGTGTGTGTACTTGTGTGTGTGTGGCATGTGTCTGCATGC
CCATGTATGAGTCTGCATGCTTTGCCTGCCTGCCTGTGTACATGTGTGTACACATGTGAATGTGTGTATT
CTTACCTGTTCTTTTCTTTTACCCTTTCTGAGAAATTAGGGTGTCTGTCCCTCATCCAGACACGATATGT
CAGGACCAGCAGTCTCATTTCCATGGAAGCCAGCCCCACCCACAGATACAGGGTAAACCCCAGCCGAATG
AGAGGGGTGGGAGTGTGGGCGGGGCAGAAGGGAGCAAGGCAGGCCTGAGCTGGTATGGCTGATGCTGGTC
TCAGTGCATGTTGAGAACCACGCTCACCTTGTTATGGTTTGTTACTCTGCAATTAAAAAGGAATAAAATG
GTCTTTCTGTTTGTTTGTTTGTTTAAGACAGTGACTCACTATGTAGCTCTTGCTCCTCTGGTCTCAATAT
GTAGTCCAGGCTAGCCTTGAATTTTCAAAGATCTGTCTGCTTCTGCCTCCCAAGTGCTGGGATTATGGGT
GTGTACTACATGGGTAGCCAAAAATTGTCTTCATGAGTTGGTCTCAGATTGGGTGAACTGGGGAGGTGTC
TTCCGTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCTTCCCTCCCTCCCT
CCCTCCCTCCCTCCCTCCCTCCCTCCCTCCCTTGTCTTCTTCCTCCTCCTTCTTTTGTCTTGAGACAGGG
TTTCTCTGTATAGCTCTGACTGTCCTAGAACTAGATCTCTTGACCAGGCTGGCTTCAAACTCAGACATTC
ACCTTTCTCTGCCTCCTGAGTGCTGGGATTAGAGGCCTGTGCTACTATGCCCACCTGGACATATGCCCTC
TTTCTACCATGTGGGTTCCAGGGATCAAATGCAGGCCACCAGGCTTGGTATCAAGCACATTTAGCTGCTG
GGCCATTTCTCCAGCCCCCACCCCTTTTAAGAGGTGGGCTTATGGTGACATTGGAGGGGTCGTTTCAGTG
ATGAAGGTCTGAGATGGCTGAGACACAGGACACTGTAGAGAGGCAGAACAGTCCCAGAGCTCCCAGAAGG
ACCAGCTGTGCCCTCACCTTCCAGCCTCTGGCCTCCAGAGCACAGAGAAAATAGACTGTGCTGTCTAAGG
CCCCAAGTCAGAGACAAATGGAGAAGCTGGTCCCAGGAAGCTGTCTACAACAAAGAATCTAATTTCCATG
TATTGTTAAATAAGAGATCCAGAATTGCAAGTCATAGGTGACAGATAAAGTTCTCGGGCTTCTGTTATTG
TACGATTATTACGTCAACTGCGATGGTAAAGATAAAAACCCAAAGCTGCATGGGGCCCCTTGGTTTAATG
ATTTTACTCCATTAAATAACACATGTGGCCATATCAAACAAGAGAAGTTGCTTTTCTTCAAACCCACTTC
AGTGATGAACTTCCCAGCACTGTGGAGACGCCATGAGGCAGAGCGTCGTGGGGGCGGGTCTGTGGGGTTT
GGGGTTTTGTTCTGTGGAGGTTTTCCCAGAAATGAGCCCTACCATAGTGTGCCATCGCCCTGGCTGGGAT
GGCTAACTCAGTCAGTTCATGCAAATCTTGCCTCTCTAGAGTCTCCTTATGAGTTTGGGGACAGATTACT
CTCCTGCAATATGCCTCAGTGCATTTTCTGTTGTGATAAAATACCAGAGGCTTGGCACTTTATAAAAAGA
AAAGGTTGATACCAGTGTGTGTGTGTTGGGGTGGGAGGGGTCCTAGTTTGCTTCCTTTTTATTAAAGACT
TATTTATTTTTTTATGTATATGAGTACAATGCAGCTGTCTTCAGACACACACTAGAAGAGTGCAGTGGAC
TCCATTACAGATGGCTGTGAGCCACCATGTGGTTGCTGGTAATTGAACTCAGGACCTCTGGAAGAGCAAT
CTGTGCTCTTAACTGCTGAGCCACCTCTCCAGTTCCCACCACCACCATGCCCGCTCGGCCCCCCAGGTTT
GCTTTTTATTTCCGTGATAAACATAGGACCAAAAGCAGTTTGGGAAGAAAAGGGGATTATTTGGCTGGTA
CAGGTCCACTTCAAAGTTTATCATTGGGAGAAATCAGGACAGGAGTTCAAAGCAGGAACCTGGAAGCAGG
AACTGAAGCAGAGACCATGGAGGACCAAGCTGTTTACCGGTTTGCTCAGTCTGCTTTCTTGGCTAACTCA
GAACCACGAGCCCAGAGAATGGCATCGCCCATAGTGAGCTGGGCCATCCCACATTAATCAAGAAAATCCC
ACACAGACTTGTCTACAGACCAGTGTGATAGAGGCAGGGGGCTCCCTCTCCCCAGATGATGGCAGCCTAC
AGGTTGACAAAAGACTGAAAAACAAAACAAAACAACAACAACAAATTCAACCCTGACCAGCATGAGGTGA
GATGTGGTTAAAGCCCTGGCTGTGCCCTGGTGTGACTAAAGGCATCATAGTGACAGTGAGTGTCATTCCT
CCTGGAATGACAAGGTTAGATCCCAGTTAAGGACTCAGAGGGGCTGTCTCACTGGAGTGTGACGTCCTTT
ACTAGGAATCTCCGCTGAATGCCATGCTCCCAGCGACCCAACCACCTTTCCCTAGGACATGCCTATTAAA
TGTCCTACCACATCCCAGCTCTGCCACATTGAAGATGAAGCCTCCCGCGTGGGAACCTGGAGGAAGGGAC
GTATCAACGCCAGGACCTCGTTCTTCCTGTTTACCTAAGGGCAGAGGTCAAGGGTAGAAACAGAATCAAG
AAACATTTAGAACAAACATAGTCCAGGCTTTCTGGAGTCTGTAGATCTGCCCACAGGCACATCCCTAACA
CTCACCCCCATATCCGGTGGCTTCTCGATCTGTCGTGCCAGACATCACACAAAGAAGAAAACGACAAGGC
AGACCAACAGATGAACAGGATCCAGAGTGACCAGAACCAGACCAGATGTCCCATGATGACATCACAGGAG
GGACCGACATTGTGGGAATGGTGCTTGAAGATGATGGTGACACTTTCTGGGAAGACCTTCCCGGATCTCC
AGAGGTACGGAACCGAGGTACGGAACCAGTGGTTACACGAATGGGGTGCTAGTCCTCAAAGGAGGAGGCC
GTGGACCCCATCACTTTACACAGAAACACCCACTTCTCACCTGCCCAGGCACCCAGAATTCCAAGAGCAA
GGTGAAGGCTTGCTCATGTCCTGGTGAAGGCTTAGTGCCTGCTTCTGTACATGGTGCAGAGAGGGATTGT
GGTGGGGGTGGGGAGACACTGGAGGGAGATGAACAAGTCAGCCGGCCCACCAGTGGTGATACTTGTCAGA
TAGCCACAGCCAGACTCTGACACAGGTGCCAACACTCTGCCTTGCGGTGCTTTCCCCCAGTCCTGGAAAT
CCTAGTTTTTCTTTATATCTGGTTGCCTTCTTTACTTAAAGCTAGAGGGGCTGGAGGGTCACCATGTCCA
CCAAATGCCTTGGGAGCAATGAGGGCTTGATTGCAGCCGGATCAGAGATGCAAGGTTACCACCGTCCATA
TGCCCTGCAGGTCCATTTGGGGTACTAAGCAGGCCAGTGTCGGCCATCATGCCTGGCCTGAGACTCTTCA
ACCAGTGCACTCAGATGTGTTGTTAATTAGAGTTTGTGTTGACATCCTCCAGGTCCAAATTTGCATGGTG
AGTCCCAACCTCCACCACTGGTCTTTGTGCCCTCCTGGTAGAGCTGTGCCCTGCCCGTGTGGTTATAATG
GGGCCATCACATGTGTGTAGAGGATGAAGACAGCCACAGTGACATGCCGGACATTTATTATGCATCAGTA
GTCTCCATCCACTGTAAGTATTAACTTCCTTATGTATACCCCGGGCTGTAGTTACACATACTGCTTAGAT
ATGAGAAAATGGGGTCCCTGATACAGGAACTTACTGAGAGTCACACAGCCATTACATGGAGAAGTGGCAG
TCAGACAGGTGATTCTCTATGGCTCTATGGCATCTCAGGATGTCACTGCTCTGTGTCACGCTGTGCTGGC
AGCCCAGGGAGTGTCTGCCCATCTTCAAGCAGGAGCAGGATGCAGATCTCCTTACTCGGAGGAGAGTTTG
GTCTCAGGGTCCCCTCTCTGGAACGTTTTGAGAAGTCACTCCTGTTGCAAACTCAGGAGAATCGTGGAAA
GAATTTCCCGAATGCCAGCTTTGTTTATTCCAATCAGCTGTAGGTTGGCTTCAGGCTTACCCAAAGCCAG
CACAAAAACCCAAACTTTCTTCCTGCTGGATTCAACACAAATCAGCCCTCAGCTGAGTCTTGGGGCTGAG
TGACATCTTTGGGGAGGGGGCAATGCTGGGGCAAGGTAGGAGTTCTAGAGAAATTGACTGCAAGTCCCAC
GGTGAGAGTGTGGTCCGTCCCCAGGTGGCACCTGTAAGCAGTAGTGTGGATAAAGTTTCTGTGATTGACA
CTTCAGCGAGGAGAAGAGATCTGTTCCTACCCCAGAGCATCCAGAGTTCAATCGGCCTCCCAAACACGCA
GAGCTTTCCTTTCAAATCACAGGAAGAACGGCCCTGCCTGGCTTGCCAGGCTGGGTTTTTCTTCTGGGTA
CCTTGTTTCCAGTGGCCCGCCAGAGTATGGCCACAGCCCAGTCCAACTTTGCAGCATCCGGGGAGGATGG
CTCTGAATTCCTGTGTTCCACCCTGCTGGCTTTCTCCAGGCACAGGCTGGGTCTCCTTGGGGAGAGAGTC
TGTGCTGCAGATCAGTCTGGGAAACGTGAGTCTCCGGCAGAATTCAGCGCTGGGGAAACCGCTGCGAAAT
TACTCCCTTCCTTCTCTGGAAGCCAGTGGACAAGAGGGCATTGTGTGGGGTCAGAGCCCTCCTGTCACAA
AGGGGCCTTTCAGAGGAGCTGACGGGGTGGGCGGGACCCCAGCCGCATGCGCTTCTGGGCACATGTCCGG
TCTTCCACGTGCACATGTGTAGGCATGTACACATGTGTGCATGTATGTATGCGCACATGTGTGTGTATGC
ATGTATGTGCACATGTGTGTATGTGCACATGTGTGCATATATGTATGTGAACATGTGTGTGGATGTGTGT
GCATATATGTGTGTATAAGTGTATGTTCACGTATGTGTGTGCATGTGTATGTGTGCGGGTATGTGTACAT
ATGTACATGTGTATACATGTGTGTATATACATGCATATGCAAATGTGTGTATGTGTGTGCATATACATGT
GTTTGCTGGGGACAGAGAGCTGTGTGTTTGTGTATTCCCTGTAAATAGGTAGAACAGAGCACTAACAAAC
ATCTCTGTTAGGAAGTTATTTCCTTGTAGGAGAAGGATCAGGCATGGGTAGGCAGTATGACTGGATCCCT
GAAAGGTACAAGTTAGGCTGTCAGCCTGGAGCTCCAGGCTTACATGTGGTGACAGATGATGTGGGGGCAA
GAAATGTAGGCCGATGGCCTTGTGGACTCTGGGTCAGCCATGTGAGAAGTTGCCCATTCAAATACTCCTG
CACCCTGGAAAGGGACAGACACATACACTCCTGAGAGAGGGAGCGGGGAGGAAGGCAGTGTGGGTAGGTG
TTTGGGATGAGAGGAGGCTTGGATCCACCTAAGTGTGAATGCTGTGTGTGCACCTGTGTGTGCATGCGTG
TGTGCCTGTGCATGCTCTGGAGAAGCTTCACTGTGTAATTGCTCTCTGCAGAGCATGGGCCACTGTGTAA
TTAAGCTGCGTGCTGGCTGCTCCCAGCACAGAAAATGATTTTGTGCGCGCTTGGCGATTACTCCGTCCCG
TTCCTTCATCAAAAATGCTGCTTCCGTTTCCCACACAAAATGGTTCCCAGACCAGGAGGAAGGCAGCCTT
CCCTGCAGCCTTGGCAAGATGGTGGCTTCTGGGAAGGAAAGACAGAGGGAGGGAGAGAAGAGGATGTCCT
CAAAGTGCAGTGACTGACATTCTGTGCTTCACCACCCAAGAAAAGTGCATTTTACAACAGGCATCCCTGC
CATCTGGCCCTATTTGGCTCCACTAGTGAACAGAAATTATTCCAAATATCCAAACCACTCAAGCTCTCTC
TCTTGCTCTCTCTCTCTCTCTCTCTCTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG
GTGTGTGTGTGTGTTTGTGTGTGTGTGTGTGTGTACAGAATATTCCCTCTGGAGCACAGGCTGCCTGGGG
ACTGGCTCAGAGTGGTGGAGTCCCTTCAAGGTCTACCCATAAGGCTACAGAAGCCATCCAGCCATCCAGA
AGGGACAGGAAAGAACATGAAGGGACTTTGGCTGGATTTTTGATAGGAATTTCAGAGCTCCCCAGAGCAT
TTTTTTTTTTAAATAGAATTGTTCCATTATGGCTATATGCCTCAGGCAAGCTAATGCAATTCTCTGAGCT
GCTTTTTGGGATTAACCGTAACAGAATGATAGCTGCCACCTTCGGTGGCTCCTGTTGTTGGAGTGAGACT
TGCTGGGAACCAGCGGGCGGGGCAGGGCTAGCAGGTGCTGCCTTTCTCATCTACAACAATGTATTTCTTT
TTATCTCTCAAGGAATCTCAGCATCAGGGTTAGCACTACCCCTCCATAAACCCTGTGATCCCCAGGACAG
GACCAGGAGGAGGCAGACAGGGTGGCTAGCACTGGGTCCCTTGTCTATCTTGGACAACTTGATAGTTTAT
TACAAGGACACATATGCAGATCCTGGCTGTGTTGCCACGAGTGAATCACCTAGCCTATCTGACCTGTGCC
TTTTGCTGGGTCCCATAAGGCTGTATTACTGGGTAGGTCCGGCTGGCTAGCTAGAATTCCTATTTAGGAG
AGGGAAGGAGATTATAGACTTTGGTGGCTAAAAGCATATGCTGCCCGGGGACTCTCAAAGCTTGACGGCC
TGCCCTGATACAGCTGTGTGGCTTTGGAAGAGAGTTCATTTCCCTGATCAGGCTCCTGCTGTCTTCTTCA
CTCTGTGAGGTAAATATGGAAAGGGGGTGCATTATAGGGGTGTCTGCCAAGAGCCCAGTGTGCATAGGCT
GCGTTTGTCACCTAGTAGGTATGGGTGTTGGGACCGAGGCTTGCCTAAGACCTGAAAGTCAAGGAAGATG
GTGGACTCAGCTGTTGAAATAGTCTTGCTACTTAGACAGGTGCATTTGTGTGTGTGTGTGTGTGTGTGTG
TGTGTGTGTGTGTGTGTGTAGTTTCTACATTTTAACTCAGTGAATTTATTAACATGACCCGGCTCCTGTG
TTTTTCAGATCAAGTTTTTGTTTGTTTGTTTTAGTTTTGTTTTGTTTTGTTTTCAAGACAGGGTTTCTCT
GTGTAGTCTTGGCTGTCCTGGAACTCACTCTGTAGTCCAGGCTGGCCCCACACTCATAGAGATTCACTTG
CCTCTGTCCCGCACGTGCTGGGCCCAGAGTCATTCACCACCAGCACCAGGCTATGCAGATCATTTAAAAA
AGACACCTGTAAAGTCTGTAGTGATGGCTCCTCCTTTGTCCTCAGTATCTGTGACTTGTGTGTTACTTTG
TTTCCTTCGGTTTCCTTTTTGGTCATTTGATACAGAGATCCATCCCCTGTATCAACTCTTTCAAAGATAC
TGCTTTGGGTCTTCATTAATTTTCTGCTTTTTCCCTATTTCCTTGTTTTTAATGTTTTCTTTGTTACATT
TACTTTTGTTTGCTTGTTTGCTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGCCAGCACATTTGTGTAGC
GATCAGAGGACCTCTCTATGGAGTTAGTTCCTTCACCATACAGGTTCCAGGGACTGAACCCAGATTATGA
GCCTTGACGCCAAGCTCCTGTACCTGCTGAGCCATCTTGCTGGTCTCTTACTCTTTTCTCATCTTTGCTC
TCCCTTGGATCTTGTGTTTAACTTGCTTCCTTCTTTTCTTCCCTAACACAGGTGCCCACAGCACCCACTT
GAGAGTCACTCCTAGCTGACATGGTACCTCAACTGGAATCCTCTATCCAAGGATCTTGTGGACCACATGA
GGCTAATTAGAATATGCTCTTCTCTGCGGCTGCTGGTCAGGGATGAGCGCTCTCCCATGTCTGCTTCTGT
TAGCCGTGAATGAGTCTGCCTTCTTTTTAAGGAATGAATATATATTCTTTGATGGTTCCATACATGTACA
CATGTACTGTCTGTTGATTATATTTTACGCCACACCCCTTACTCCCCCATGTCTTCCCAAAATCTCTTCT
CTCTCCTCTCTTCTCCCTCCCCTCCATCCTCTTCCTTCTCCTCCTCCTCTTCTTTAAAACCACACCCAGT
CCAGTGAGTGTTGCCTGAACACACATGGGCATTGAGCCATCCCAGGGACTTGGGCAACCTACCAGCAGTC
ATCCATACCTTTGGAGAAGCTCGGCCGTCCTTCCTTGGAAGCATCCATTGTAAGTAGATCTTCACCCAGG
GATGGGATTTTATGAGCCTCTCCCGTCCATGCTGGATATTGACTGACTCCATCGTGTGTGAATCACCACA
GCTGCTGTGAGTTCGTGAATCCGATGCTCACACATCGTGGCCAGAGGACAGCATTTCACTCCCCTCTCCC
AGCCTCTAGCTTTGATGTTCTTTCTGCTTCCTCTCCCATAATGTCCCCTGAGCTTCACAGGGGATAGGTG
GATATAGGTGTCCCATCAGGGGTGAACACTCACGGTCACTTACTGTTAGCACTTTGATCAAGCCGTGAGT
CCCAGCACTAACCACTACACTGGAAGAAACAGCTTCCTGAGCAATGCTAATTTATGGATATAAATAGAAA
TATTGAGAAGGCAATTTGACAGCGTGTCCATTTAACCGGTAGTTTCTCCCCTAGGGCCTATGACCTCCGG
ACCCACAGCTTTTGACTAGGTGCATGGCACTAGATTTGTGTTCCCTCCTCTGAAGCAGACCTCAGATCCC
GTCAGAAAACGGGTGGCTCCCACAACCACCATGCCTCTATGGCACTGGTAGCAGGGCTTGCTTTGGCTTT
GTTCCTTAACTTCCAGCTACCTTGAGATCTTCTAGGCAGCTCCCCTGCAGCCAGAGGACCAGCTATTCAG
CTGCGTGTGACAGATGACAATGTTCCTTCCCCTACCCGCCTGCCCACCCAGAGCTCTGACCTGGTGTCAG
CCTCTTGTGCTGAATGGAGGCATCTACAGCTGCTGGGTGAGTACTCTGAATTCCCTGATGTCAAAATGAC
GCTCGGGAATGTGCCAGCCTCATGAGTCTGTTGGTCTGTCTCACTCATTCACTCCATCAGCTGAGGGTGG
GATCTGAACAGATCCGGTTATGCATCATGTATATCACTGGGATGTGTACCGAGAGTCACCATGGAAACCT
GGGTATGGGACTCAGAGTCACCATGGAAACCAGCCACTGGGTATGCCTGTCAGGAAGCTTCTAGAGTGTG
TTCACGGAAGTGGGAAGAGCCACCCTGCGTGTTGGCAGTGCCATCTCTTCGTGATCTGGGGTCCTGGACA
GAATGAAAAGGAGCAAGCAAGTGGAGTACCAGCAGTCACCCCTCTCTGCTTCCTGACTGTGGGTGCCATG
TGACCAGCTGTTTCATGTTCCTGCCACTGTGCCTCCCCGCCATGACGGACTGTGCACGCTCACACTGTGA
GCCAGCGCGAACCCTTCCTTCTTTAAGGTGCTTTTTGTTACAGCGGTGAGACGACGGCTAATATGCTGCA
GAAACACGTGCACGGTGTGCAGGGCTCACGTGGACGACACAATCCCTGCTGCATCTCATTTGACTAGCTC
TCAGCATCTGCTTCAGCCGCTCTTCTAGGAAACCACTCTTATTCTTCTGGACTCTCTTTTGCTCATAAAT
TAAAATGCAAATTCTATCACTGACCGTGTATAATTAACTCCCTGTCCCAGGTTGGTACATCTGTGTCCTG
TCACAGTTGGACTCTGCCCTCACCCCTGGATCATGGGGCTCCAGCAGCCCAGATGCCCACCTGGGCTTAT
GTAGCTATCCGAGCACAGCTGGGGAGGAATCAGAGCACAGCTGGGAAGGAGTGAGAGCTGGGTGGTGCCA
GCTGCACCAGAGTCCAGGTTCATGCTGCAGACTTGAAAAGATCTGTGATGAAAAGGAACTGTCTCTGAGA
GCAGGAGTAGAGCACTGCTCAGGGTGGGCAAGCCTGAGAGCAGAGCCTGGCGCTTTGGGTCTCACTAGTG
CAGGGCTCTGTCCTGTGCAGCCCTGGCTGTCCTTTGCAGCGAGTGAAGGGTGAAGAGAGCAGCGAGTTTT
TTTGGCAGAGGAAAAGACACGGAACGCCCAACCACAGGATTCCCAAAAACAATGCTAAGCATTAATCTTG
CTAACATGTTAGATGGCACGCAGGTCTCCGCAGGCTCATTCCTGGGCTAGACACAGTTCCCAAAAGCCAT
CCGATTCCGCATCCCCCCTGGCCATGTGTGGGTAATGAGCAGATGCATCTGGGCTGGCCCTGGCCTCCCA
GCCACGTGGGGCCAGACCTTCCCCAGCTCTGGCCTAGGCCTGCCATAGGGAATACCTTAAGCATCCTCCT
CTGCCTTGTCCTCCTGCCCTTGGTGAAGACTAGGGCAAATATGCTCAGAGGGGTTCTCCAGCCACAGCCT
CACAGTGGCTCTGCCTCCCAACCATGCAGTGTCTCATAGGGGACAGGCTAAACGAAGAGGCAGCTAGAGT
AACGTCTCTCAGGTCTTGACTCACAGACATCATTTCCATGGTTTTCTTTGAAAGACACATACACACAACC
AAACCGATTTTAATTAGAGATTTTGTTTTGTGGTCAGGCGGCCACAAGTGAGGGCAGGGTAGCTTTCATG
TGAGGAACATACACAGGACTGAGCCTGTTTCCCATAAAAGGATACTCCCCTCCCCACGCCTCCCCAACCA
AATGGGAAAAGAGTTTGTTTTGCACAGTTTGGGAATGCTAGGCAAAGCTGTCTTTTGCAAAGTCTGCAGT
TGAGGGTCTCCCCACAGCAGCCTCTGTGGATGTTGGAGTAACTGGGGCATTTGTCAGCCTCCGGTGCCTG
CTGGGATCATGCACACAGAGGTTAGACATTCAGTCCTGACTGTAACACAAAAACTAGCCGAGAACCAAGT
TAGCACACCCAGGAGCACCCGGACGCTTCCAGGCTTGAGCCAATGAGTACAATGTGATAAGTACTGTAGA
ATGAGCACCACACCATGAGCATTGTGTGATGAGCACTGTGCAATGAGTACTATGTGATAAGTACTGAACA
GTGAACACCACATGAGCACTGTGTGATGAGCACTTTGTGATGAGTACTATGTGATAAGTACTGTAGAATG
AGTACCACACTGTGCGCACTCTGTGATGAGCACTGTGCAAGGCGCGCTGTGGAATGAGTACACCACAGGT
GCTGTACACCCCGGGTTGGAGCTGGGATCAGGGCTGTACCAGTCTTCACACTCAGAAGGTGGCTTCTCTG
TCCTGTGCAGGACGACACGCGTCCTATCAGAGGCTCACACCCTTTGACACAGGACGAGTGTCTCAGGTCG
GTTTCATAGAGCAGAGCAGGAACCGCCAGGCCCCTCGTAGCCCAGAGCTTCCCACAGGGTGGCACCCTCT
CCGTGTAGCCAGAGTCTCTTGCACTGGGTTGCAGTGGTCTCCAGGTGAGAATGGCAAAAGAGCAAACGGG
AGCTTTGAGAAGGAGGACTCCTCTCTGCTTCACCGGTGGCCCCAGGGCAGTGGCTCTCTCCTGTGTGACA
CCCTCTTACCCTCTGCCCTCACACACCTTTGTTCAAGATGGCTACTTCAAGTTCCACGCATTGCCTACAT
TTCCAGCCAGCAGGAACGAGGACTGCCTCGAAGGAAGGGTGGGGACTCTGGTCAGCTGATTGCTGCGTTT
AGGGGATAAGATGAACAAATTCTTACCTTAATCTTATTAGCCATAGCGCGGTCACATAATCTCAGCTACC
AGCAAAGGAGGCTGGGAGGCGTGGCTTGACTTCCAGGTGTATGTATACCTGGGTCCAGGGCCTGCTCCTT
TCGTTCCTGTGTGTCCCTAGTGTTCACAGCAGAGTCGGGACTGTGGGAGGGGTGTGTGTGTGTTTGATTT
TTTTTCTAGACAGGGTTTCTCTGTATAGCCCTGGCTGTCCTGGAACTCACTTTGTAGACCAGACTAGCCT
CGAACTCAGAAATCCGCCTGCCTCTGCCTCCCAAGTGCTGGGATTAAAGGCATGCGCCACCACCGCTCGG
CGTGGGAGGGTTTTTGCCATGGGACAAATGTGTGCCTGATGTAGCAGAGGGACTGACACAGTCCTAACTG
GGACTCACTGCCCGGTCTCGCGACGTATGATGGATCGGGTAGAGTGCAGTGACTCCAGAGTCCATATTTT
ACCATGGCAAGGGTGAGAACATGTGGTCTACAGAGAGAGCTTGCTCTCTTCAGAAGCCAAGAGCTCTCTC
CTTTTGCCTGGGTCATTTCACAATTTCACCCCTCAAACACCAGGCTAGCCCTTGCAGAGAATGTCCCAGT
TACCCTGTGCAGTAAGTACTATGTGATAAATACTGAACAATGAGCACCACACAAGAGCAGTGTGCAGTGA
GAACTGGAACTACACCCCAACCTCCTGACTTCACGTCGGATTCCCCGGAAGGCTCGCCCAGAGTGAGCAC
ACAGGTCTCAAGAGTTAAATGTCCTGTTGGCAGGCAGTTGGGCATTTTATTTCCTGGTTCTGTTAGTTCT
GTCACCATCTGCAGCAGGGAAGGACCAGATTCAGGGGCCCATCATTTATTTCCTCAAGGGATGGGGCCAC
TGAGGCGTCTGGGGCTTTTTAGAAAAGAGGCCTCCTGATCCAGGATTCCCACCCTTGGCACACTCCAGCC
CTGACTCCAGCCCTGGATGTCTGAGGCTCTGTTTCCACCCATGACAGTGCCCTGGGGCTCTCTCCAGCTT
ACTTCAGCATAAAGTTACCAAGGAACCTCTGCCAGGAACAGAAACTTCGAGGCTCAAAGAACTGGGTGAC
CTCAAGAAATTAAGAGACAGCTGGACAGAGGACATTCATGAGCCTGGGTTCCAACTGGGGTAGATATCTG
GAAACGGGCTGACTTCTTCCCAGTGTCTGCATCCCAAGAACGTGGCTCTGTAACTCCCAAGTCGGAGACC
AGGGATACTGCTCAGTTGGTCGAGCGCCTAACATAGGAGAAGCCGTGGGTTCCACCCAGGGCATAGACCA
GCTGTGATGGACATGCCAGTAATCGCAGCACTGGGGAGGTAGAGGCAGTAGAGGCAGGATAAATTTAAGT
GTATCCTGGGCTACATAGTGAACTTGGGGCTATCCTGAGCTATACCAAACCCTTTTTAAAAAATGAAATC
CCAACTCCAGTGAAAAGCCTGTTCTGAGCCTCTGCATCTTACCCCATTCCTCCTCAAGAATGTGGTGCTA
AGCTAGCCACCATTACCCACCTTTCCTTTGGGGGTTGGTAAGCTACCCAGATAGCCTGCCGTGCAGCGGA
GGGAAGGGGTTCACAAGCTTGGTCCTTGCTAACTGTCCCTCCTGCCTGCCTGCCTGGCCTGATAACCTGG
CTGCATTTGGAAATAAATGACACATTTTCCTTACATCTGCTCCAAATTTTCGTTTCAGAAATTAGAGCGC
TCCGTTCCGTGGTATTACGCGGCGGCACTCCACGGGCCTGGGAGTGCAGAGCTGATTGGATGTCCCACCC
AAAGGAGAGACGGTTCAAGCTCTTTCCAGGAAATTGAGTGGAACACCCAAACTGACATCCAATATTAAAT
ATTGTATTTGTGGACTTGT`,
      textarea: '',
      show:false,
     word_size:'11',
     options2:[
       {value:'5',label:'5'},
       {value:'6',label:'6'},
       {value:'7',label:'7'},
       {value:'8',label:'8'},
       {value:'9',label:'9'},
       {value:'10',label:'10'},
       {value:'11',label:'11'},
       
     ],
      // 设置eValue下拉框选项
      options1: [
          {
          value: '1e-3',
          label: '1e-3'
          },{
          value: '1e-4',
          label: '1e-4'
          },{
          value: '1e-5',
          label: '1e-5 '
          },{
          value: '1e-6',
          label: '1e-6 '
          },{
          value: '1e-7',
          label: '1e-7 '
          }],
      // 设置eValue默认值
      eValue: '1e-7',
      resData:[],
      tableData:[],
      urlNCBI:"https://www.ncbi.nlm.nih.gov/gene/",
      isShow:true,
      ShowSeq:"",
      tableLoading:false,
      length:10,
      
      
    }
  },
  methods: {
    SearchExample(){
      //显示example数据
      this.textarea = this.example;
    },
    evalue_change(val){
      this.eValue = val;
    },
    word_change(val){
      this.word_size = val;
    },
    Search(eValue,word_size){
      ElLoading.service({
        fullscreen:true,
        text:"Loading...",
        background:"rgba(0,0,0,0.7)"
      });


      
      var _this = this
      _this.show = true;
      axios.post("api/property/blast",{
          user_seq: _this.textarea,
          user_wordSize: word_size,
          user_eValue: eValue
      }).then(respond =>{
        ElLoading.service({
          fullscreen:true,
          text:"Loading...",
          background:"rgba(0,0,0,0.7)"
        });
        console.log(respond.data.message.data.length)
        _this.length=respond.data.message.data.length
        if(respond.data.message.data.length == 1){
          window.alert("Blast Query is Empty!")
        }
        // this.tableLoading=true;
        for(let i = 0;i<respond.data.message.data.length;i++){
          let resData = respond.data.message.data[i];
          if(resData != ""){
            let qseqid = resData.split('\t')[0];
            let sseqid = resData.split('\t')[1];
            let pident = resData.split('\t')[2];
            let length = resData.split('\t')[3];
            let evalue = resData.split('\t')[4];
            let bitscore = resData.split('\t')[5];
            // console.log(qseqid,sseqid,pident,length,evalue,bitscore)

            axios.post("api/property/fuzzySeq",{user_sseqid:sseqid}).then(function( respond ){  

              _this.length--;
              _this.LoadingClose();
              let Name = respond.data[0]["Name"];
              let NONCODEId = respond.data[0]["NONCODEId"];
              let NCBI_gene_Id = respond.data[0]["NCBI_gene_Id"];
              let Aliases_fullName = respond.data[0]["Aliases"];
              let Reason = respond.data[0]["Reason"];
              let Organism = respond.data[0]["Organism"];
              let Gene_Ontology_Annotations = respond.data[0]["Gene_Ontology_Annotations"];
              let Sequence = respond.data[0]["fasta"];
              let result = {
                "qseqid":qseqid,
                "sseqid":sseqid,
                "pident":pident,
                "length":length,
                "evalue":evalue,
                "bitscore":bitscore,
                "Name":Name,
                "NONCODEId":NONCODEId,
                "NCBI_gene_Id":NCBI_gene_Id,
                "Aliases_fullName":Aliases_fullName,
                "Reason":Reason,
                "Organism":Organism,
                "Gene_Ontology_Annotations":Gene_Ontology_Annotations,
                "Sequence":Sequence
                // "Sequence":Sequence.substr(0,100),
                // "SequenceJq":Sequence.substr(0,100),
                // "Sequenceqb":Sequence,
                
              };           
              // console.log(result)
              _this.tableData.push(result)
              
            })
          }
        }
        
        // let loadingInstance = ElLoading.service({});
        //   this.$nextTick(() => {
        // // 以服务的方式调用的 Loading 需要异步关闭
        //   loadingInstance.close();
        // });
      }).catch(err=>{
        console.log(err)
      })

    
          
    },

    LoadingClose (){
      if(this.length=== 1){
        let loadingInstance = ElLoading.service({});
        this.$nextTick(() => {
       // 以服务的方式调用的 Loading 需要异步关闭
          loadingInstance.close();
        });
      }
    },
    toUrl_NONCODE(data){
      window.location.href = "http://www.noncode.org/show_rna.php?id="+data.split(".")[0]+"&version="+data.split(".")[1]+"&utd=1#"
    },
    toUrl_NCBI(data){
      window.location.href = "https://www.ncbi.nlm.nih.gov/gene/"+data

    }
    // kzClick(i) {
    //   if(this.isShow){
    //     this.tableData[i].Sequence = this.tableData[i].Sequenceqb;
    //   }
    //   else{
    //     this.tableData[i].Sequence = this.tableData[i].SequenceJq;
    //   }
    //   this.isShow=!this.isShow;
    // }

  }

}
</script>

<style scoped>
.el-select{
  width: 150px !important;
}
.el-input{
  width: 150px;
}
.el-select-dropdown__item{
  text-align: center !important;
}
</style>
<style scoped lang="less">
.myForm {
  margin: 10px auto; /* 表单居中设置 */
  padding: 40px 60px;
  width: 75%;
  border: 3px solid #b4ede7;
  border-radius: 10px;
}

.el-table {
  font-size: 15px;
  white-space: pre-line;
  //color: #232324;
}
.demo-table-expand {
    font-size: 0;
}
.demo-table-expand label {
  width: 90px;
  color: #99a9bf;
}
.demo-table-expand {
  margin-right: 0;
  margin-bottom: 0;
  width: 100%;
}
:deep(.el-form-item__label) {
  font-size: 15px;
  //color: #232324;
}

.title {
  text-align: center;
  font-size: 1.5em;
  line-height: 80px;
  height: 80px;
  background: #e6f0ef; /* Old browsers */
  background: -moz-linear-gradient(
    -45deg,
    #e6f0ef 45%,
    #b4ede7 100%
  ); /* FF3.6-15 */
  background: -webkit-linear-gradient(
    -45deg,
    #e6f0ef 45%,
    #b4ede7 100%
  ); /* Chrome10-25,Safari5.1-6 */
  background: linear-gradient(
    135deg,
    #e6f0ef 45%,
    #b4ede7 100%
  ); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e6f0ef', endColorstr='#b4ede7',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
}

.el-form-item {
  border-top: 1px solid #ebeef5; // 表格线条颜色
  margin-bottom: 0;
}

.el-form-item :deep(.el-form-item__label)  {
  border-right: 1px solid #ebeef5;
}


// /deep/ 相当于 >>>
:deep(.el-input__inner:hover) {
  // background-color: rgb(115, 200, 200) !important;
  border-color: rgb(115, 200, 200) !important;
}

:deep(.el-input .is-active .el-input__inner.el-input__inner:focus)  {
  border-color: rgb(115, 200, 200) !important;
}

:deep( .el-radio__inner:hover) {
  background-color: rgb(115, 200, 200) !important;
  border-color: rgb(115, 200, 200) !important;
}
// 单选框的标签可以换行了
:deep(.all_label)  {
  display: inline-grid;
  white-space: pre-line;
  word-wrap: break-word;
  overflow: hidden;
  line-height: 20px;
}
:deep(.el-checkbox__input.is-checked + .el-checkbox__label) {
  color: rgb(115, 200, 200) !important;
}
:deep(.el-checkbox__input.is-checked .el-checkbox__inner)  {
  background-color: rgb(115, 200, 200) !important;
  border-color: rgb(115, 200, 200) !important;
}
:deep(.el-checkbox__label){
  padding-left: 5px;
}
:deep(.el-radio__input.is-checked + .el-radio__label)  {
  color: rgb(115, 200, 200) !important;
}
:deep(.el-radio__input.is-checked .el-radio__inner){
  background-color: rgb(115, 200, 200) !important;
  border-color: rgb(115, 200, 200) !important;
}
:deep(.el-radio__label) {
  padding-left: 5px;
  font-size: 15px;
  color: #232324;
}
:deep(.el-textarea__inner){
  border-color: rgb(115, 200, 200) !important;
  font-size: 15px;
  color: #232324;
}
:deep(.el-select .el-input__inner:focus)  {
  border-color: rgb(115, 200, 200);
}

.el-select {
  margin-left: 10px;
}

.el-select-dropdown__item.selected {
  color: rgb(115, 200, 200);
}

.el-select-dropdown__item {
  text-align: center;
  text-indent: 0;
}


// 遮盖原始按钮，以改变原始按钮的样式
.upload {
  height: 35px;
  line-height: 35px;
  //   position: relative;
  font-size: 15px;
  width: 100px;
  border-radius: 5px;
  color: #fff;
  background-color: #5cb85c;
  margin: auto 30px;
  outline: none;
  cursor: pointer;
}

// 选择文件的原始按钮
.change {
  position: absolute;
  overflow: hidden;
  width: 100px;
  line-height: 35px;
  left: 30px;
  top: 20px;
  opacity: 0; // 设为透明
  cursor: pointer;
}

.submit {
  font-size: 15px;
  height: 35px;
  width: 120px;
  border-radius: 5px;
  color: #fff;
  background-color: #337ab7;
  border: #337ab7;
  margin: auto 10px; // 按钮居中
  outline: none;
  cursor: pointer;
}

.myemail {
  font-size: 15px;
  height: 35px;
  width: 120px;
  border-radius: 5px;
  color: #fff;
  background-color: #e6a23c;
  border: #e6a23c;
  margin: 10px 10px 10px; // 按钮居中
}

.progress-wrap {
  width: 100%;
  margin: 0 auto;
  // border-left: 1px solid #ebeef5;
  p {
    margin: 0 auto;
    width: 100%;
    font-size: 15px;
  }
  .progress {
    background-color: #c5c8ce;
    height: 15px;
    span {
      display: block;
      background-color: #19be6b;
      height: 100%;
      width: 0;
    }
  }
}
span {
  display:inline-block;
  // 在span标签中，可设置输出的内容截断 
  word-wrap:break-word; 
  word-break: break-all; 
  white-space:normal ; 
  width:100%;
  font-size:15px;
  font-family:"Avenir", Helvetica, Arial, sans-serif;
} 

.hand:hover{
  color:#1ee3cf;
  cursor:pointer
}
.newlist {
  position: relative;
  margin: 0 auto;
  width: 80%;
  min-height: 30px;
  line-height: 20px;
  /* border: 1px solid ; */
  word-break: break-all;
  hyphens: auto;
  text-align: left;
  padding: 5px 10px;
  background:#f2f4f6;
  font-family:monospace;
}
.open_style{
  height:18px;
  width:18px;
}
.sou{
  font-weight:700;
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  font-size:15px;

}
/deep/ .el-button span {
  font-weight:700;
  font-family: "Avenir", Helvetica, Arial, sans-serif;
  font-size:15px;
}
</style>
